[workspace]
members = [
    "catseq-core",
    "catseq-frontend",
    "catseq-python",
    "catseq-runtime",
    "catseq-rtmq",
]
resolver = "3"

[workspace.package]
version = "0.4.2"
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
anyhow = "1.0"
catseq-core = { path = "catseq-core" }
catseq-frontend = { path = "catseq-frontend" }
catseq-runtime = { path = "catseq-runtime" }
catseq-rtmq = { path = "catseq-rtmq" }
libc = "0.2"
nac3ast = { git = "https://github.com/hirobumii/nac3.git", rev = "dbf7d72e0ec4b232e8b5e2258ae4d5b6ec9b5f8e" }
nac3core = { git = "https://github.com/hirobumii/nac3.git", rev = "dbf7d72e0ec4b232e8b5e2258ae4d5b6ec9b5f8e" }
nac3parser = { git = "https://github.com/hirobumii/nac3.git", rev = "dbf7d72e0ec4b232e8b5e2258ae4d5b6ec9b5f8e" }
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10"
toml = "0.8"
