[package]
name = "catseq-frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "catseq_frontend"

[dependencies]
anyhow.workspace = true
catseq-core = { path = "../catseq-core" }
nac3ast.workspace = true
nac3core.workspace = true
nac3parser.workspace = true
parking_lot.workspace = true
serde.workspace = true
sha3.workspace = true
