name: CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up CatSeq Environment
      run: |
        # The setup script needs to be executable
        chmod +x ./setup.sh
        # Run the setup script to create venv, install deps, and run post-install
        ./setup.sh

    - name: Lint with ruff
      run: |
        source .venv/bin/activate
        ruff check .

    - name: Check types with mypy
      continue-on-error: true
      run: |
        source .venv/bin/activate
        mypy .

    - name: Run tests with pytest
      run: |
        source .venv/bin/activate
        pytest